name: erdos_may_2024_v2
channels:
  - conda-forge
dependencies:
  - jupyter 
  - matplotlib >= 3.8
  - openpyxl >= 3.0
  - pandas >= 2.1
  - pip = 24.0
  - pyarrow 
  - py-xgboost
  - python >=3.7
  - scikit-learn = 1.4.2
  - seaborn
  - sqlalchemy
  - tensorflow = 2.15
  - xgboost = 2.0.3
  - pmdarima > 2.0
  - pip:
      - cinemagoer
      - lxml
      - pynytimes
